# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kspacr < Formula
  desc ""
  homepage "https://kspacr.com"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kspacr/kspacr-cli/releases/download/v0.6.0/kspacr-cli_darwin_x86_64.tar.gz"
      sha256 "adc8823b4d34b583e87875f3a2ace3819a356a07e78f956659e951c2c0802eb0"

      def install
        bin.install "kspacr"

        bash_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "bash")
        (bash_completion/"kspacr").write bash_output
        zsh_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "zsh")
        (zsh_completion/"_kspacr").write zsh_output
        fish_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "fish")
        (fish_completion/"kspacr.fish").write fish_output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kspacr/kspacr-cli/releases/download/v0.6.0/kspacr-cli_darwin_arm64.tar.gz"
      sha256 "c4f7bd09df21d11bde40b275f394f7fbe235b2898a511cbfe080c4ec9e8ae142"

      def install
        bin.install "kspacr"

        bash_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "bash")
        (bash_completion/"kspacr").write bash_output
        zsh_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "zsh")
        (zsh_completion/"_kspacr").write zsh_output
        fish_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "fish")
        (fish_completion/"kspacr.fish").write fish_output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kspacr/kspacr-cli/releases/download/v0.6.0/kspacr-cli_linux_aarch64.tar.gz"
      sha256 "02593d855438c439bf13f7bbed3070768934e7a072d35946b27d384198b56dda"

      def install
        bin.install "kspacr"

        bash_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "bash")
        (bash_completion/"kspacr").write bash_output
        zsh_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "zsh")
        (zsh_completion/"_kspacr").write zsh_output
        fish_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "fish")
        (fish_completion/"kspacr.fish").write fish_output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kspacr/kspacr-cli/releases/download/v0.6.0/kspacr-cli_linux_x86_64.tar.gz"
      sha256 "0bd6833c876c7efd713b53c322dcaaf92a38332157ea685655e878e633b1063a"

      def install
        bin.install "kspacr"

        bash_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "bash")
        (bash_completion/"kspacr").write bash_output
        zsh_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "zsh")
        (zsh_completion/"_kspacr").write zsh_output
        fish_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "fish")
        (fish_completion/"kspacr.fish").write fish_output
      end
    end
  end

  test do
    system "#{bin}/kspacr version"
  end
end
