# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kspacr < Formula
  desc ""
  homepage "https://kspacr.com"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kspacr/kspacr-cli/releases/download/v0.1.1/kspacr-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "941634ca27e3e66870105073c5f214c9ef4141d1ad85941361b55a13a45c6d9f"

      def install
        bin.install "kspacr"

        bash_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "bash")
        (bash_completion/"kspacr").write bash_output
        zsh_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "zsh")
        (zsh_completion/"_kspacr").write zsh_output
        fish_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "fish")
        (fish_completion/"kspacr.fish").write fish_output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kspacr/kspacr-cli/releases/download/v0.1.1/kspacr-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "513cea0551574945f9281e6b312a405cfd175a44c7b7c5fe58f37cca52c04d97"

      def install
        bin.install "kspacr"

        bash_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "bash")
        (bash_completion/"kspacr").write bash_output
        zsh_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "zsh")
        (zsh_completion/"_kspacr").write zsh_output
        fish_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "fish")
        (fish_completion/"kspacr.fish").write fish_output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kspacr/kspacr-cli/releases/download/v0.1.1/kspacr-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "3515095d3bba610d0742e86a26ce5c842186432bc18f4dc1d72831449c8c3c4a"

      def install
        bin.install "kspacr"

        bash_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "bash")
        (bash_completion/"kspacr").write bash_output
        zsh_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "zsh")
        (zsh_completion/"_kspacr").write zsh_output
        fish_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "fish")
        (fish_completion/"kspacr.fish").write fish_output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kspacr/kspacr-cli/releases/download/v0.1.1/kspacr-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "f2ad2d011ea3c5e386e539cf8b52a59b2b6eb2c108688408b227a8b7647a13c4"

      def install
        bin.install "kspacr"

        bash_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "bash")
        (bash_completion/"kspacr").write bash_output
        zsh_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "zsh")
        (zsh_completion/"_kspacr").write zsh_output
        fish_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "fish")
        (fish_completion/"kspacr.fish").write fish_output
      end
    end
  end

  test do
    system "#{bin}/kspacr version"
  end
end
