# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kspacr < Formula
  desc ""
  homepage "https://kspacr.com"
  version "0.4.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kspacr/kspacr-cli/releases/download/v0.4.2/kspacr-cli_0.4.2_darwin_x86_64.tar.gz"
      sha256 "cd825dbe93dc2516ac80e5387ad4f685577acccccd9a89fb7ccf02ce61febdf2"

      def install
        bin.install "kspacr"

        bash_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "bash")
        (bash_completion/"kspacr").write bash_output
        zsh_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "zsh")
        (zsh_completion/"_kspacr").write zsh_output
        fish_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "fish")
        (fish_completion/"kspacr.fish").write fish_output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kspacr/kspacr-cli/releases/download/v0.4.2/kspacr-cli_0.4.2_darwin_arm64.tar.gz"
      sha256 "228478081de36c475d3374b6f3fb4ede88cfe0a6662e13ec5b70018eb396776e"

      def install
        bin.install "kspacr"

        bash_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "bash")
        (bash_completion/"kspacr").write bash_output
        zsh_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "zsh")
        (zsh_completion/"_kspacr").write zsh_output
        fish_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "fish")
        (fish_completion/"kspacr.fish").write fish_output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kspacr/kspacr-cli/releases/download/v0.4.2/kspacr-cli_0.4.2_linux_x86_64.tar.gz"
      sha256 "afef58be0046846a7c6164900b11355157ea6dfb4527ab867e5c016b71584c4c"

      def install
        bin.install "kspacr"

        bash_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "bash")
        (bash_completion/"kspacr").write bash_output
        zsh_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "zsh")
        (zsh_completion/"_kspacr").write zsh_output
        fish_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "fish")
        (fish_completion/"kspacr.fish").write fish_output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kspacr/kspacr-cli/releases/download/v0.4.2/kspacr-cli_0.4.2_linux_arm64.tar.gz"
      sha256 "e99242964d7a593aa5ce68c0e84667e136be3afb32147a62d0ebe8ea1ab72948"

      def install
        bin.install "kspacr"

        bash_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "bash")
        (bash_completion/"kspacr").write bash_output
        zsh_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "zsh")
        (zsh_completion/"_kspacr").write zsh_output
        fish_output = Utils.safe_popen_read("#{bin}/kspacr", "completion", "fish")
        (fish_completion/"kspacr.fish").write fish_output
      end
    end
  end

  test do
    system "#{bin}/kspacr version"
  end
end
